/**
 * AI Service (OpenAI-compatible chat completions)
 *
 * P3: Provides an AI assistant capability using any OpenAI-compatible
 * chat/completions API (OpenAI, Azure OpenAI, OpenRouter, Together,
 * Groq, local Ollama, etc.) so the app is provider-agnostic.
 *
 * Configuration (backend/.env):
 *   - AI_API_KEY  (or OPENAI_API_KEY)  — API key for the provider
 *   - AI_BASE_URL  — API base URL, default https://api.openai.com/v1
 *   - AI_MODEL     — model id, default gpt-4o-mini
 *   - AI_PROVIDER  — optional human-readable label, default 'openai-compatible'
 *   - AI_DISABLED=1 — force-disable even if a key is present
 *
 * No key configured → runs in DEV MODE: returns a deterministic, clearly
 * labeled mock reply instead of crashing, so local development keeps working
 * without paid credentials.
 */

const axios = require('axios');

const getBaseUrl = () => (process.env.AI_BASE_URL || 'https://api.openai.com/v1').replace(/\/+$/, '');
const getApiKey = () => process.env.AI_API_KEY || process.env.OPENAI_API_KEY || '';
const getModel = () => process.env.AI_MODEL || 'gpt-4o-mini';
const getProviderLabel = () => process.env.AI_PROVIDER || 'openai-compatible';

const isDisabled = () => process.env.AI_DISABLED === '1' || process.env.AI_DISABLED === 'true';
const hasAICreds = () => Boolean(getApiKey()) && !isDisabled();

class AIService {
  constructor() {
    if (!hasAICreds()) {
      console.warn('[AI] No AI credentials configured — running in DEV MODE. AI replies are simulated and NOT produced by a real model. Set AI_API_KEY (and optionally AI_BASE_URL/AI_MODEL) in your .env to enable real completions.');
    }
  }

  isEnabled() {
    return hasAICreds();
  }

  /**
   * Complete a chat conversation.
   * @param {Object} opts
   * @param {string} [opts.system] - System prompt.
   * @param {Array<{role: string, content: string}>} opts.messages - Chat history.
   * @param {number} [opts.maxTokens] - Max output tokens (default 500).
   * @param {number} [opts.temperature] - Sampling temperature (default 0.7).
   * @returns {Promise<{content: string, provider: string, model: string, mock: boolean}>}
   */
  async completeChat(opts = {}) {
    const system = opts.system;
    const messages = Array.isArray(opts.messages) ? opts.messages : [];
    const maxTokens = Number(opts.maxTokens) || 500;
    const temperature = opts.temperature != null ? Number(opts.temperature) : 0.7;

    const payloadMessages = [];
    if (system) payloadMessages.push({ role: 'system', content: String(system) });
    if (messages.length === 0) {
      throw new Error('No chat messages provided');
    }
    for (const m of messages) {
      if (!m || typeof m.content !== 'string') continue;
      payloadMessages.push({ role: m.role === 'assistant' ? 'assistant' : 'user', content: m.content });
    }
    if (payloadMessages.length === 0) {
      throw new Error('No chat messages provided');
    }

    if (!hasAICreds()) {
      return this._mockReply(payloadMessages[payloadMessages.length - 1].content, system);
    }

    const response = await axios.post(
      `${getBaseUrl()}/chat/completions`,
      {
        model: getModel(),
        messages: payloadMessages,
        max_tokens: maxTokens,
        temperature
      },
      {
        headers: {
          Authorization: `Bearer ${getApiKey()}`,
          'Content-Type': 'application/json'
        },
        timeout: 30000
      }
    );

    const content = response.data?.choices?.[0]?.message?.content;
    if (typeof content !== 'string' || !content) {
      throw new Error('AI provider returned an empty completion');
    }

    return {
      content,
      provider: getProviderLabel(),
      model: getModel(),
      mock: false
    };
  }

  _mockReply(lastUserContent, system) {
    const topic = String(lastUserContent || '').trim().slice(0, 60);
    const systemNote = system ? ` System prompt: "${String(system).trim().slice(0, 60)}"` : '';
    return {
      content: `[DEV MODE mock reply — no AI_API_KEY configured, so this text was not generated by a real model.] Your message was: "${topic}". Enable AI in production by setting AI_API_KEY.${systemNote}`,
      provider: 'dev-mode',
      model: 'mock',
      mock: true
    };
  }
}

module.exports = new AIService();
