import React, { useState, useEffect } from 'react';
import { Globe, Check } from 'lucide-react';

const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
];

const translations = {
  en: {
    'chat': 'Chat',
    'status': 'Status',
    'calls': 'Calls',
    'settings': 'Settings',
    'search': 'Search',
    'typing': 'typing...',
    'recording': 'recording...',
    'message': 'Message',
    'send': 'Send',
    'reply': 'Reply',
    'forward': 'Forward',
    'delete': 'Delete',
    'star': 'Star',
    'unstar': 'Unstar',
    'copy': 'Copy',
    'edit': 'Edit',
    'save': 'Save',
    'cancel': 'Cancel',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'you': 'You',
    'me': 'Me',
    'online': 'online',
    'last_seen': 'last seen',
    'at': 'at',
    'voice_call': 'Voice call',
    'video_call': 'Video call',
    'missed_call': 'Missed call',
    'incoming_call': 'Incoming call',
    'outgoing_call': 'Outgoing call',
    'group_created': 'Group created',
    'you_changed_subject': 'You changed the subject',
    'subject_changed_to': 'Subject changed to',
    'you_were_added': 'You were added',
    'you_left': 'You left',
    'you_are_now_admin': 'You are now an admin',
    'image': 'Image',
    'video': 'Video',
    'audio': 'Audio',
    'document': 'Document',
    'sticker': 'Sticker',
    'gif': 'GIF',
    'location': 'Location',
    'contact': 'Contact',
    'voice_message': 'Voice message',
    'photo': 'Photo',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'document_title': 'Document',
    'file': 'File',
    'wallpaper': 'Wallpaper',
    'language': 'Language',
    'theme': 'Theme',
    'dark_mode': 'Dark mode',
    'light_mode': 'Light mode',
    'notifications': 'Notifications',
    'privacy': 'Privacy',
    'security': 'Security',
    'storage': 'Storage',
    'data_usage': 'Data usage',
    'help': 'Help',
    'about': 'About',
    'logout': 'Logout',
    'profile': 'Profile',
    'name': 'Name',
    'about_info': 'About',
    'phone': 'Phone',
    'email': 'Email',
    'address': 'Address',
    'birthday': 'Birthday',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'add_contact': 'Add contact',
    'new_group': 'New group',
    'new_broadcast': 'New broadcast',
    'group_info': 'Group info',
    'group_name': 'Group name',
    'group_subject': 'Group subject',
    'group_description': 'Group description',
    'group_settings': 'Group settings',
    'participants': 'Participants',
    'add_participant': 'Add participant',
    'remove_participant': 'Remove participant',
    'admin': 'Admin',
    'member': 'Member',
    'mute': 'Mute',
    'unmute': 'Unmute',
    'block': 'Block',
    'unblock': 'Unblock',
    'report': 'Report',
    'clear_chat': 'Clear chat',
    'delete_chat': 'Delete chat',
    'archive': 'Archive',
    'unarchive': 'Unarchive',
    'archived': 'Archived',
    'starred_messages': 'Starred messages',
    'no_messages': 'No messages yet',
    'no_chats': 'No chats yet',
    'start_conversation': 'Start a conversation',
    'send_message': 'Send a message',
    'loading': 'Loading...',
    'connecting': 'Connecting...',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'reconnecting': 'Reconnecting...',
    'error': 'Error',
    'try_again': 'Try again',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'update': 'Update',
    'download': 'Download',
    'upload': 'Upload',
    'share': 'Share',
    'export': 'Export',
    'import': 'Import',
    'backup': 'Backup',
    'restore': 'Restore',
    'sync': 'Sync',
    'syncing': 'Syncing...',
    'synced': 'Synced',
    'done': 'Done',
    'complete': 'Complete',
    'in_progress': 'In progress',
    'pending': 'Pending',
    'failed': 'Failed',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm': 'Confirm',
    'are_you_sure': 'Are you sure?',
    'this_action_cannot_be_undone': 'This action cannot be undone',
    'delete_message': 'Delete message',
    'delete_for_me': 'Delete for me',
    'delete_for_everyone': 'Delete for everyone',
    'message_deleted': 'Message deleted',
    'this_message_was_deleted': 'This message was deleted',
    'view_deleted_message': 'View deleted message',
    'restore_message': 'Restore message',
    'message_restored': 'Message restored',
    'copy_text': 'Copy text',
    'text_copied': 'Text copied',
    'select_text': 'Select text',
    'search_in_chat': 'Search in chat',
    'search_messages': 'Search messages',
    'no_results': 'No results',
    'found': 'found',
    'of': 'of',
    'next': 'Next',
    'previous': 'Previous',
    'close': 'Close',
    'open': 'Open',
    'view': 'View',
    'hide': 'Hide',
    'show': 'Show',
    'more': 'More',
    'less': 'Less',
    'see_all': 'See all',
    'show_all': 'Show all',
    'load_more': 'Load more',
    'loading_more': 'Loading more...',
    'end_of_list': 'End of list',
    'scroll_to_top': 'Scroll to top',
    'scroll_to_bottom': 'Scroll to bottom',
    'new_message': 'New message',
    'new_messages': 'New messages',
    'unread': 'Unread',
    'read': 'Read',
    'mark_as_read': 'Mark as read',
    'mark_as_unread': 'Mark as unread',
    'mark_all_as_read': 'Mark all as read',
    'seen': 'Seen',
    'delivered': 'Delivered',
    'sent': 'Sent',
    'sending': 'Sending...',
    'failed_to_send': 'Failed to send',
    'tap_to_send': 'Tap to send',
    'recording_audio': 'Recording audio...',
    'recording_video': 'Recording video...',
    'processing': 'Processing...',
    'uploading': 'Uploading...',
    'downloading': 'Downloading...',
    'preparing': 'Preparing...',
    'compressing': 'Compressing...',
    'extracting': 'Extracting...',
    'converting': 'Converting...',
    'encoding': 'Encoding...',
    'decoding': 'Decoding...',
    'encrypting': 'Encrypting...',
    'decrypting': 'Decrypting...',
    'encrypted': 'Encrypted',
    'end_to_end_encrypted': 'End-to-end encrypted',
    'messages_are_encrypted': 'Messages are end-to-end encrypted',
    'tap_for_more_info': 'Tap for more info',
    'learn_more': 'Learn more',
    'privacy_policy': 'Privacy policy',
    'terms_of_service': 'Terms of service',
    'version': 'Version',
    'build': 'Build',
    'copyright': 'Copyright',
    'all_rights_reserved': 'All rights reserved',
    'made_with_love': 'Made with ❤️',
    'genz_whatsapp': 'GENZ WhatsApp',
    'genz_mods': 'GENZ Mods',
    'mods': 'Mods',
    'enable': 'Enable',
    'disable': 'Disable',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'on': 'On',
    'off': 'Off',
    'true': 'True',
    'false': 'False',
    'auto': 'Auto',
    'manual': 'Manual',
    'default': 'Default',
    'custom': 'Custom',
    'advanced': 'Advanced',
    'basic': 'Basic',
    'simple': 'Simple',
    'complex': 'Complex',
    'fast': 'Fast',
    'slow': 'Slow',
    'high': 'High',
    'low': 'Low',
    'medium': 'Medium',
    'maximum': 'Maximum',
    'minimum': 'Minimum',
    'unlimited': 'Unlimited',
    'limited': 'Limited',
    'free': 'Free',
    'paid': 'Paid',
    'premium': 'Premium',
    'pro': 'Pro',
    'basic_plan': 'Basic',
    'standard_plan': 'Standard',
    'premium_plan': 'Premium',
    'upgrade': 'Upgrade',
    'downgrade': 'Downgrade',
    'subscribe': 'Subscribe',
    'unsubscribe': 'Unsubscribe',
    'subscription': 'Subscription',
    'trial': 'Trial',
    'free_trial': 'Free trial',
    'days': 'Days',
    'day': 'Day',
    'hours': 'Hours',
    'hour': 'Hour',
    'minutes': 'Minutes',
    'minute': 'Minute',
    'seconds': 'Seconds',
    'second': 'Second',
    'ago': 'ago',
    'just_now': 'Just now',
    'in': 'in',
    'from': 'From',
    'to': 'To',
    'and': 'and',
    'or': 'or',
    'with': 'with',
    'without': 'without',
    'by': 'by',
    'for': 'for',
    'as': 'as',
    'if': 'if',
    'when': 'when',
    'where': 'where',
    'why': 'why',
    'how': 'how',
    'what': 'what',
    'who': 'who',
    'which': 'which',
    'that': 'that',
    'this': 'this',
    'these': 'these',
    'those': 'those',
    'here': 'here',
    'there': 'there',
    'now': 'now',
    'then': 'then',
    'always': 'always',
    'never': 'never',
    'sometimes': 'sometimes',
    'often': 'often',
    'rarely': 'rarely',
    'maybe': 'maybe',
    'probably': 'probably',
    'definitely': 'definitely',
    'certainly': 'certainly',
    'sure': 'sure',
    'of_course': 'Of course',
    'please': 'Please',
    'thank_you': 'Thank you',
    'thanks': 'Thanks',
    'you_are_welcome': 'You\'re welcome',
    'sorry': 'Sorry',
    'excuse_me': 'Excuse me',
    'goodbye': 'Goodbye',
    'bye': 'Bye',
    'see_you': 'See you',
    'take_care': 'Take care',
    'have_a_nice_day': 'Have a nice day',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'good_night': 'Good night',
    'hello': 'Hello',
    'hi': 'Hi',
    'hey': 'Hey',
    'welcome': 'Welcome',
    'congratulations': 'Congratulations',
    'happy_birthday': 'Happy birthday',
    'happy_holiday': 'Happy holiday',
    'merry_christmas': 'Merry Christmas',
    'happy_new_year': 'Happy new year',
    'best_wishes': 'Best wishes',
    'good_luck': 'Good luck',
    'take_your_time': 'Take your time',
    'no_rush': 'No rush',
    'no_problem': 'No problem',
    'no_worries': 'No worries',
    'dont_worry': 'Don\'t worry',
    'be_careful': 'Be careful',
    'watch_out': 'Watch out',
    'look_out': 'Look out',
    'attention': 'Attention',
    'notice': 'Notice',
    'important': 'Important',
    'urgent': 'Urgent',
    'emergency': 'Emergency',
    'help_me': 'Help me',
    'call_police': 'Call police',
    'call_ambulance': 'Call ambulance',
    'call_fire_department': 'Call fire department',
    'i_need_help': 'I need help',
    'are_you_ok': 'Are you okay?',
    'im_fine': 'I\'m fine',
    'im_good': 'I\'m good',
    'im_great': 'I\'m great',
    'im_busy': 'I\'m busy',
    'im_tired': 'I\'m tired',
    'im_hungry': 'I\'m hungry',
    'im_thirsty': 'I\'m thirsty',
    'im_sick': 'I\'m sick',
    'im_cold': 'I\'m cold',
    'im_hot': 'I\'m hot',
    'im_happy': 'I\'m happy',
    'im_sad': 'I\'m sad',
    'im_angry': 'I\'m angry',
    'im_excited': 'I\'m excited',
    'im_surprised': 'I\'m surprised',
    'im_confused': 'I\'m confused',
    'im_scared': 'I\'m scared',
    'im_worried': 'I\'m worried',
    'im_stressed': 'I\'m stressed',
    'im_bored': 'I\'m bored',
    'im_lonely': 'I\'m lonely',
    'im_jealous': 'I\'m jealous',
    'im_proud': 'I\'m proud',
    'im_embarrassed': 'I\'m embarrassed',
    'im_nervous': 'I\'m nervous',
    'im_shy': 'I\'m shy',
    'im_curious': 'I\'m curious',
    'im_interested': 'I\'m interested',
    'im_bored': 'I\'m bored',
    'im_excited': 'I\'m excited',
    'im_motivated': 'I\'m motivated',
    'im_inspired': 'I\'m inspired',
    'im_creative': 'I\'m creative',
    'im_productive': 'I\'m productive',
    'im_efficient': 'I\'m efficient',
    'im_effective': 'I\'m effective',
    'im_successful': 'I\'m successful',
    'im_confident': 'I\'m confident',
    'im_determined': 'I\'m determined',
    'im_focused': 'I\'m focused',
    'im_ready': 'I\'m ready',
    'im_prepared': 'I\'m prepared',
    'im_set': 'I\'m set',
    'im_going': 'I\'m going',
    'im_coming': 'I\'m coming',
    'im_leaving': 'I\'m leaving',
    'im_staying': 'I\'m staying',
    'im_waiting': 'I\'m waiting',
    'im_working': 'I\'m working',
    'im_studying': 'I\'m studying',
    'im_learning': 'I\'m learning',
    'im_teaching': 'I\'m teaching',
    'im_playing': 'I\'m playing',
    'im_watching': 'I\'m watching',
    'im_listening': 'I\'m listening',
    'im_reading': 'I\'m reading',
    'im_writing': 'I\'m writing',
    'im_drawing': 'I\'m drawing',
    'im_painting': 'I\'m painting',
    'im_singing': 'I\'m singing',
    'im_dancing': 'I\'m dancing',
    'im_cooking': 'I\'m cooking',
    'im_eating': 'I\'m eating',
    'im_drinking': 'I\'m drinking',
    'im_sleeping': 'I\'m sleeping',
    'im_dreaming': 'I\'m dreaming',
    'im_thinking': 'I\'m thinking',
    'im_feeling': 'I\'m feeling',
    'im_hoping': 'I\'m hoping',
    'im_wishing': 'I\'m wishing',
    'im_wondering': 'I\'m wondering',
    'im_guessing': 'I\'m guessing',
    'im_assuming': 'I\'m assuming',
    'im_believing': 'I\'m believing',
    'im_knowing': 'I\'m knowing',
    'im_understanding': 'I\'m understanding',
    'im_realizing': 'I\'m realizing',
    'im_remembering': 'I\'m remembering',
    'im_forgetting': 'I\'m forgetting',
    'im_imagining': 'I\'m imagining',
    'im_creating': 'I\'m creating',
    'im_building': 'I\'m building',
    'im_making': 'I\'m making',
    'im_doing': 'I\'m doing',
    'im_having': 'I\'m having',
    'im_getting': 'I\'m getting',
    'im_giving': 'I\'m giving',
    'im_taking': 'I\'m taking',
    'im_bringing': 'I\'m bringing',
    'im_sending': 'I\'m sending',
    'im_receiving': 'I\'m receiving',
    'im_buying': 'I\'m buying',
    'im_selling': 'I\'m selling',
    'im_paying': 'I\'m paying',
    'im_spending': 'I\'m spending',
    'im_saving': 'I\'m saving',
    'im_investing': 'I\'m investing',
    'im_earning': 'I\'m earning',
    'im_losing': 'I\'m losing',
    'im_winning': 'I\'m winning',
    'im_trying': 'I\'m trying',
    'im_testing': 'I\'m testing',
    'im_checking': 'I\'m checking',
    'im_verifying': 'I\'m verifying',
    'im_confirming': 'I\'m confirming',
    'im_validating': 'I\'m validating',
    'im_approving': 'I\'m approving',
    'im_rejecting': 'I\'m rejecting',
    'im_accepting': 'I\'m accepting',
    'im_declining': 'I\'m declining',
    'im_agreeing': 'I\'m agreeing',
    'im_disagreeing': 'I\'m disagreeing',
    'im_supporting': 'I\'m supporting',
    'im_opposing': 'I\'m opposing',
    'im_helping': 'I\'m helping',
    'im_hindering': 'I\'m hindering',
    'im_encouraging': 'I\'m encouraging',
    'im_discouraging': 'I\'m discouraging',
    'im_praising': 'I\'m praising',
    'im_criticizing': 'I\'m criticizing',
    'im_complimenting': 'I\'m complimenting',
    'im_insulting': 'I\'m insulting',
    'im_thanking': 'I\'m thanking',
    'im_apologizing': 'I\'m apologizing',
    'im_greeting': 'I\'m greeting',
    'im_farewelling': 'I\'m farewelling',
    'im_introducing': 'I\'m introducing',
    'im_presenting': 'I\'m presenting',
    'im_explaining': 'I\'m explaining',
    'im_describing': 'I\'m describing',
    'im_narrating': 'I\'m narrating',
    'im_reporting': 'I\'m reporting',
    'im_announcing': 'I\'m announcing',
    'im_declaring': 'I\'m declaring',
    'im_stating': 'I\'m stating',
    'im_expressing': 'I\'m expressing',
    'im_communicating': 'I\'m communicating',
    'im_discussing': 'I\'m discussing',
    'im_talking': 'I\'m talking',
    'im_speaking': 'I\'m speaking',
    'im_saying': 'I\'m saying',
    'im_telling': 'I\'m telling',
    'im_asking': 'I\'m asking',
    'im_answering': 'I\'m answering',
    'im_responding': 'I\'m responding',
    'im_replying': 'I\'m replying',
    'im_questioning': 'I\'m questioning',
    'im_wondering': 'I\'m wondering',
  },
  sw: {
    'chat': 'Mazungumzo',
    'status': 'Hali',
    'calls': 'Simu',
    'settings': 'Mipangilio',
    'search': 'Tafuta',
    'typing': 'anaandika...',
    'recording': 'anarekodi...',
    'message': 'Ujumbe',
    'send': 'Tuma',
    'reply': 'Jibu',
    'forward': 'Peleka',
    'delete': 'Futa',
    'star': 'Weka alama',
    'unstar': 'Ondoa alama',
    'copy': 'Nakili',
    'edit': 'Hariri',
    'save': 'Hifadhi',
    'cancel': 'Ghairi',
    'ok': 'Sawa',
    'yes': 'Ndiyo',
    'no': 'Hapana',
    'today': 'Leo',
    'yesterday': 'Jana',
    'you': 'Wewe',
    'me': 'Mimi',
    'online': 'mtandaoni',
    'last_seen': 'alionekana mwisho',
    'at': 'saa',
    'voice_call': 'Simu ya sauti',
    'video_call': 'Simu ya video',
    'missed_call': 'Simu isiyopatikana',
    'incoming_call': 'Simu inayoingia',
    'outgoing_call': 'Simu inayotoka',
    'image': 'Picha',
    'video': 'Video',
    'audio': 'Sauti',
    'document': 'Nyaraka',
    'sticker': 'Stika',
    'gif': 'GIF',
    'location': 'Eneo',
    'contact': 'Mawasiliano',
    'voice_message': 'Ujumbe wa sauti',
    'photo': 'Picha',
    'camera': 'Kamera',
    'gallery': 'Galeria',
    'file': 'Faili',
    'wallpaper': 'Mandhari',
    'language': 'Lugha',
    'theme': 'Mandhari',
    'dark_mode': 'Hali ya giza',
    'light_mode': 'Hali ya mwanga',
    'notifications': 'Arifa',
    'privacy': 'Faragha',
    'security': 'Usalama',
    'storage': 'Hifadhi',
    'data_usage': 'Matumizi ya data',
    'help': 'Msaada',
    'about': 'Kuhusu',
    'logout': 'Toka',
    'profile': 'Wasifu',
    'name': 'Jina',
    'about_info': 'Kuhusu',
    'phone': 'Simu',
    'email': 'Barua pepe',
    'add_contact': 'Ongeza mawasiliano',
    'new_group': 'Kundi jipya',
    'group_info': 'Maelezo ya kundi',
    'group_name': 'Jina la kundi',
    'participants': 'Washiriki',
    'admin': 'Msimamizi',
    'member': 'Mwanachama',
    'mute': 'Zima sauti',
    'unmute': 'Washa sauti',
    'block': 'Zuia',
    'unblock': 'Ondoa kizuizi',
    'report': 'Ripoti',
    'clear_chat': 'Futa mazungumzo',
    'delete_chat': 'Futa mazungumzo',
    'archive': 'Hifadhi kwenye archivi',
    'unarchive': 'Ondoa kwenye archivi',
    'starred_messages': 'Ujumbe ulioalamishwa',
    'no_messages': 'Hakuna ujumbe bado',
    'no_chats': 'Hakuna mazungumzo bado',
    'start_conversation': 'Anza mazungumzo',
    'loading': 'Inapakia...',
    'connecting': 'Inaunganisha...',
    'connected': 'Imeunganishwa',
    'disconnected': 'Imekatizwa',
    'reconnecting': 'Inaunganisha tena...',
    'error': 'Hitilafu',
    'try_again': 'Jaribu tena',
    'retry': 'Jaribu tena',
    'refresh': 'Onyesha upya',
    'update': 'Sasisha',
    'download': 'Pakua',
    'upload': 'Pakia',
    'share': 'Shiriki',
    'export': 'Hamisha',
    'import': 'Ingiza',
    'backup': 'Hifadhi nakala',
    'restore': 'Rudisha',
    'sync': 'Sawazisha',
    'done': 'Imekamilika',
    'complete': 'Kamilisha',
    'in_progress': 'Inaendelea',
    'pending': 'Inasubiri',
    'failed': 'Imeshindwa',
    'success': 'Imefanikiwa',
    'warning': 'Onyo',
    'info': 'Maelezo',
    'confirm': 'Thibitisha',
    'are_you_sure': 'Una uhakika?',
    'this_action_cannot_be_undone': 'Hatua hii haiwezi kufutwa',
    'delete_message': 'Futa ujumbe',
    'delete_for_me': 'Futa kwangu',
    'delete_for_everyone': 'Futa kwa wote',
    'message_deleted': 'Ujumbe umefutwa',
    'this_message_was_deleted': 'Ujumbe huu ulifutwa',
    'copy_text': 'Nakili maandishi',
    'text_copied': 'Maandishi yamenakiliwa',
    'search_in_chat': 'Tafuta kwenye mazungumzo',
    'search_messages': 'Tafuta ujumbe',
    'no_results': 'Hakuna matokeo',
    'found': 'imepatikana',
    'of': 'ya',
    'next': 'Ifuatayo',
    'previous': 'Iliyotangulia',
    'close': 'Funga',
    'open': 'Fungua',
    'view': 'Tazama',
    'hide': 'Ficha',
    'show': 'Onyesha',
    'more': 'Zaidi',
    'less': 'Chache',
    'see_all': 'Ona yote',
    'show_all': 'Onyesha yote',
    'load_more': 'Pakia zaidi',
    'loading_more': 'Inapakia zaidi...',
    'end_of_list': 'Mwisho wa orodha',
    'scroll_to_top': 'Sogeza juu',
    'scroll_to_bottom': 'Sogeza chini',
    'new_message': 'Ujumbe mpya',
    'new_messages': 'Ujumbe mpya',
    'unread': 'Hazijasomwa',
    'read': 'Zimesomwa',
    'mark_as_read': 'Alama kama zimesomwa',
    'mark_as_unread': 'Alama kama hazijasomwa',
    'mark_all_as_read': 'Alama zote kama zimesomwa',
    'seen': 'Zimeonekana',
    'delivered': 'Zimefikishwa',
    'sent': 'Zimetumwa',
    'sending': 'Inatuma...',
    'failed_to_send': 'Imeshindwa kutuma',
    'tap_to_send': 'Gusa kutuma',
    'recording_audio': 'Inarekodi sauti...',
    'recording_video': 'Inarekodi video...',
    'processing': 'Inachakata...',
    'uploading': 'Inapakia...',
    'downloading': 'Inapakua...',
    'encrypted': 'Imesimbwa',
    'end_to_end_encrypted': 'Imesimbwa kwa njia ya mwisho hadi mwisho',
    'messages_are_encrypted': 'Ujumbe umesimbwa kwa njia ya mwisho hadi mwisho',
    'tap_for_more_info': 'Gusa kwa maelezo zaidi',
    'learn_more': 'Jifunze zaidi',
    'privacy_policy': 'Sera ya faragha',
    'terms_of_service': 'Sheria za huduma',
    'version': 'Toleo',
    'build': 'Jenga',
    'copyright': 'Hakimiliki',
    'all_rights_reserved': 'Haki zote zimehifadhiwa',
    'made_with_love': 'Imetengenezwa kwa ❤️',
    'genz_whatsapp': 'GENZ WhatsApp',
    'genz_mods': 'GENZ Mods',
    'mods': 'Mods',
    'enable': 'Washa',
    'disable': 'Zima',
    'enabled': 'Imewashwa',
    'disabled': 'Imezimwa',
    'on': 'Washa',
    'off': 'Zima',
    'default': 'Chaguomsingi',
    'custom': 'Maalum',
    'advanced': 'Hali ya juu',
    'basic': 'Msingi',
    'fast': 'Haraka',
    'slow': 'Polepole',
    'high': 'Juu',
    'low': 'Chini',
    'medium': 'Kati',
    'maximum': 'Upeo',
    'minimum': 'U chini',
    'unlimited': 'Bila kikomo',
    'limited': 'Limiti',
    'free': 'Bure',
    'paid': 'Imelipwa',
    'premium': 'Premiamu',
    'pro': 'Pro',
    'upgrade': 'Boresha',
    'downgrade': 'Punguza',
    'subscribe': 'Jisajili',
    'unsubscribe': 'Jiondoe',
    'subscription': 'Usajili',
    'trial': 'Majaribio',
    'free_trial': 'Majaribio ya bure',
    'days': 'Siku',
    'day': 'Siku',
    'hours': 'Masaa',
    'hour': 'Saa',
    'minutes': 'Dakika',
    'minute': 'Dakika',
    'seconds': 'Sekunde',
    'second': 'Sekunde',
    'ago': 'iliyopita',
    'just_now': 'Hivi punde',
    'in': 'katika',
    'from': 'kutoka',
    'to': 'kwa',
    'and': 'na',
    'or': 'au',
    'with': 'na',
    'without': 'bila',
    'by': 'na',
    'for': 'kwa',
    'as': 'kama',
    'if': 'kama',
    'when': 'linapo',
    'where': 'wapi',
    'why': 'kwa nini',
    'how': 'jinsi',
    'what': 'nini',
    'who': 'nani',
    'which': 'ambayo',
    'that': 'hiyo',
    'this': 'hii',
    'these': 'hizi',
    'those': 'zile',
    'here': 'hapa',
    'there': 'huko',
    'now': 'sasa',
    'then': 'kisha',
    'always': 'daima',
    'never': 'kamwe',
    'sometimes': 'wakati mwingine',
    'often': 'mara nyingi',
    'rarely': 'nadra',
    'maybe': 'labda',
    'probably': 'labda',
    'definitely': 'hakika',
    'certainly': 'hakika',
    'sure': 'hakika',
    'of_course': 'Bila shaka',
    'please': 'Tafadhali',
    'thank_you': 'Asante',
    'thanks': 'Asante',
    'you_are_welcome': 'Karibu',
    'sorry': 'Samahani',
    'excuse_me': 'Samahani',
    'goodbye': 'Kwaheri',
    'bye': 'Bye',
    'see_you': 'Tutaonana',
    'take_care': 'Jitunze',
    'have_a_nice_day': 'Uwe na siku njema',
    'good_morning': 'Habari ya asubuhi',
    'good_afternoon': 'Habari ya mchana',
    'good_evening': 'Habari ya jioni',
    'good_night': 'Usiku mwema',
    'hello': 'Hello',
    'hi': 'Hi',
    'hey': 'Hey',
    'welcome': 'Karibu',
    'congratulations': 'Hongera',
    'happy_birthday': 'Heri ya siku ya kuzaliwa',
    'happy_holiday': 'Heri ya likizo',
    'merry_christmas': 'Krismasi Njema',
    'happy_new_year': 'Heri ya Mwaka Mpya',
    'best_wishes': 'Matakwa mema',
    'good_luck': 'Bahati njema',
    'take_your_time': 'Chukua muda wako',
    'no_rush': 'Hakuna haraka',
    'no_problem': 'Hakuna shida',
    'no_worries': 'Hakuna wasiwasi',
    'dont_worry': 'Usiwasi',
    'be_careful': 'Kuwa makini',
    'watch_out': 'Tazama',
    'look_out': 'Tazama',
    'attention': 'Tahadhari',
    'notice': 'Tahadhari',
    'important': 'Muhimu',
    'urgent': 'Haraka',
    'emergency': 'Dharura',
    'help_me': 'Nisaidie',
    'call_police': 'Pigia polisi',
    'call_ambulance': 'Pigia ambulansi',
    'call_fire_department': 'Pigia idara ya zima moto',
    'i_need_help': 'Nahitaji msaada',
    'are_you_ok': 'U mzima?',
    'im_fine': 'Mzima',
    'im_good': 'Sijambo',
    'im_great': 'Niko sawa',
    'im_busy': 'Niko busy',
    'im_tired': 'Nimechoka',
    'im_hungry': 'Nina njaa',
    'im_thirsty': 'Nina kiu',
    'im_sick': 'Mgonjwa',
    'im_cold': 'Nina baridi',
    'im_hot': 'Nina joto',
    'im_happy': 'Nina furaha',
    'im_sad': 'Nina huzuni',
    'im_angry': 'Nimekasirika',
    'im_excited': 'Nina shauku',
    'im_surprised': 'Nimeshangaa',
    'im_confused': 'Nimechanganyikiwa',
    'im_scared': 'Ninaogopa',
    'im_worried': 'Nina wasiwasi',
    'im_stressed': 'Nina mkazo',
    'im_bored': 'Nimezuka',
    'im_lonely': 'Nina upweke',
    'im_jealous': 'Nina wivu',
    'im_proud': 'Nina kiburi',
    'im_embarrassed': 'Nimeaibika',
    'im_nervous': 'Nina wasiwasi',
    'im_shy': 'Nina aibu',
    'im_curious': 'Nina udadisi',
    'im_interested': 'Nina hamu',
    'im_motivated': 'Nina motisha',
    'im_inspired': 'Nimehamasika',
    'im_creative': 'Nina ubunifu',
    'im_productive': 'Nina tija',
    'im_efficient': 'Nina ufanisi',
    'im_effective': 'Nina ufanisi',
    'im_successful': 'Nina mafanikio',
    'im_confident': 'Nina ujasiri',
    'im_determined': 'Nina azma',
    'im_focused': 'Nina mkazo',
    'im_ready': 'Niko tayari',
    'im_prepared': 'Nimejiandaa',
    'im_set': 'Niko seti',
    'im_going': 'Naenda',
    'im_coming': 'Nakuja',
    'im_leaving': 'Naondoka',
    'im_staying': 'Ninakaa',
    'im_waiting': 'Ninasubiri',
    'im_working': 'Ninafanya kazi',
    'im_studying': 'Ninasoma',
    'im_learning': 'Ninajifunza',
    'im_teaching': 'Ninafundisha',
    'im_playing': 'Ninacheza',
    'im_watching': 'Ninatazama',
    'im_listening': 'Ninasikiliza',
    'im_reading': 'Ninasoma',
    'im_writing': 'Ninaandika',
    'im_drawing': 'Ninachora',
    'im_painting': 'Ninapaka rangi',
    'im_singing': 'Ninaimba',
    'im_dancing': 'Ninacheza densi',
    'im_cooking': 'Ninapika',
    'im_eating': 'Ninala',
    'im_drinking': 'Ninanywa',
    'im_sleeping': 'Ninalala',
    'im_dreaming': 'Ninaota',
    'im_thinking': 'Ninafikiria',
    'im_feeling': 'Ninahisi',
    'im_hoping': 'Nina tumaini',
    'im_wishing': 'Nina tamaa',
    'im_wondering': 'Nina shangaa',
    'im_guessing': 'Nina dhania',
    'im_assuming': 'Nina dhania',
    'im_believing': 'Ninaamini',
    'im_knowing': 'Ninajua',
    'im_understanding': 'Ninaelewa',
    'im_realizing': 'Ninatambua',
    'im_remembering': 'Ninakumbuka',
    'im_forgetting': 'Ninasahau',
    'im_imagining': 'Ninawaza',
    'im_creating': 'Ninaunda',
    'im_building': 'Ninajenga',
    'im_making': 'Ninatengeneza',
    'im_doing': 'Ninafanya',
    'im_having': 'Nina',
    'im_getting': 'Ninapata',
    'im_giving': 'Ninatoa',
    'im_taking': 'Ninachukua',
    'im_bringing': 'Ninaleta',
    'im_sending': 'Ninatuma',
    'im_receiving': 'Ninapokea',
    'im_buying': 'Ninanunua',
    'im_selling': 'Ninauza',
    'im_paying': 'Ninalipa',
    'im_spending': 'Ninatumia',
    'im_saving': 'Ninahifadhi',
    'im_investing': 'Ninawekeza',
    'im_earning': 'Ninapata',
    'im_losing': 'Ninapoteza',
    'im_winning': 'Ninashinda',
    'im_trying': 'Ninajaribu',
    'im_testing': 'Ninajaribu',
    'im_checking': 'Ninakagua',
    'im_verifying': 'Ninathibitisha',
    'im_confirming': 'Ninathibitisha',
    'im_validating': 'Ninathibitisha',
    'im_approving': 'Ninaidhinisha',
    'im_rejecting': 'Ninakataa',
    'im_accepting': 'Ninakubali',
    'im_declining': 'Ninakataa',
    'im_agreeing': 'Ninakubali',
    'im_disagreeing': 'Sikubali',
    'im_supporting': 'Ninaunga mkono',
    'im_opposing': 'Ninaopinga',
    'im_helping': 'Ninasaidia',
    'im_hindering': 'Ninakwamisha',
    'im_encouraging': 'Ninahimiza',
    'im_discouraging': 'Ninakata tamaa',
    'im_praising': 'Ninasifu',
    'im_criticizing': 'Ninalaumu',
    'im_complimenting': 'Ninamsifu',
    'im_insulting': 'Ninamtukana',
    'im_thanking': 'Ninamshukuru',
    'im_apologizing': 'Ninaomba msamaha',
    'im_greeting': 'Ninasalimu',
    'im_farewelling': 'Ninakwambia kwaheri',
    'im_introducing': 'Ninamwanzisha',
    'im_presenting': 'Ninawasilisha',
    'im_explaining': 'Ninaeleza',
    'im_describing': 'Ninaelezea',
    'im_narrating': 'Ninasimulia',
    'im_reporting': 'Ninaripoti',
    'im_announcing': 'Ninatangaza',
    'im_declaring': 'Ninatangaza',
    'im_stating': 'Ninasema',
    'im_expressing': 'Ninaonyesha',
    'im_communicating': 'Ninawasiliana',
    'im_discussing': 'Ninajadili',
    'im_talking': 'Ninaongea',
    'im_speaking': 'Ninaongea',
    'im_saying': 'Ninasema',
    'im_telling': 'Ninaambia',
    'im_asking': 'Ninauliza',
    'im_answering': 'Ninajibu',
    'im_responding': 'Ninajibu',
    'im_replying': 'Ninajibu',
    'im_questioning': 'Ninauliza',
    'im_wondering': 'Ninashangaa',
  },
};

const LanguageSelector = ({ currentLanguage, onLanguageChange }) => {
  const [isOpen, setIsOpen] = useState(false);

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key;
  };

  const currentLang = LANGUAGES.find(l => l.code === currentLanguage) || LANGUAGES[0];

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 bg-[#202c33] hover:bg-[#37404a] rounded-lg transition-colors text-white"
      >
        <Globe size={18} />
        <span>{currentLang.nativeName}</span>
      </button>

      {isOpen && (
        <div className="absolute top-full left-0 mt-2 w-56 bg-[#233138] rounded-lg shadow-2xl z-[1000] overflow-hidden">
          <div className="p-2">
            {LANGUAGES.map((lang) => (
              <button
                key={lang.code}
                onClick={() => {
                  onLanguageChange(lang.code);
                  setIsOpen(false);
                }}
                className={`w-full flex items-center justify-between px-3 py-2 rounded-lg transition-colors ${
                  currentLanguage === lang.code
                    ? 'bg-[#00a884] text-white'
                    : 'text-gray-300 hover:bg-white/10'
                }`}
              >
                <span>{lang.nativeName}</span>
                {currentLanguage === lang.code && <Check size={16} />}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export { LanguageSelector, translations, t };
export default LanguageSelector;