import React, { useState } from 'react';

// Local mirror of the Twemoji sticker assets (frontend/public/stickers/twemoji),
// generated by `npm run fetch:twemoji`. Used when the jsDelivr CDN is
// unreachable so stickers don't render as broken images.
const LOCAL_TWEMOJI_BASE = '/stickers/twemoji';

// If the URL is a jsDelivr Twemoji asset (the one CDN the sticker catalog
// depends on), map it to the same file served from the app's own origin.
const toLocalTwemojiUrl = (src) => {
  if (typeof src !== 'string') return null;
  const match = src.match(/twemoji@14\.0\.2\/assets\/72x72\/([a-z0-9-]+)\.png$/i);
  if (!match) return null;
  return `${LOCAL_TWEMOJI_BASE}/${match[1]}.png`;
};

// Neutral placeholder shown when every image source has failed and no emoji
// text is available — always better than a broken-image icon.
const FALLBACK_GLYPH = '🙂';

const hasEmojiChar = (text) =>
  typeof text === 'string' && /\p{Extended_Pictographic}/u.test(text);

// Sticker artwork with a fallback chain so stickers never appear as broken
// images: primary URL → local Twemoji mirror → emoji text (or a neutral
// placeholder glyph). `emoji` is the raw emoji character to render as text;
// `fallbackClassName` styles that text (defaults to a large centered emoji).
const StickerImage = ({
  src,
  emoji,
  alt = 'Sticker',
  className = '',
  fallbackClassName = '',
  ...rest
}) => {
  const [stage, setStage] = useState(0); // 0 = primary, 1 = local mirror, 2 = emoji text
  const localSrc = toLocalTwemojiUrl(src);

  // No source at all → nothing to load, go straight to the text fallback.
  if (stage === 2 || !src) {
    return (
      <span
        role="img"
        aria-label={alt}
        className={`flex items-center justify-center select-none text-center leading-none ${fallbackClassName || 'text-5xl'} ${className}`}
        {...rest}
      >
        {emoji || FALLBACK_GLYPH}
      </span>
    );
  }

  return (
    <img
      src={stage === 1 && localSrc ? localSrc : src}
      alt={alt}
      className={className}
      loading="lazy"
      onError={() => {
        if (stage === 0 && localSrc) setStage(1);
        else setStage(2);
      }}
      {...rest}
    />
  );
};

export default StickerImage;
export { hasEmojiChar };
