import React, { useState, useEffect } from 'react';
import { Mic, FileText, Download, Copy, Check, X, Loader2, Languages, Volume2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const VoiceTranscription = ({ audioUrl, onTranscriptionComplete, language = 'en' }) => {
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [transcription, setTranscription] = useState('');
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState(null);
  const [selectedLanguage, setSelectedLanguage] = useState(language);

  const languages = [
    { code: 'en', name: 'English' },
    { code: 'sw', name: 'Swahili' },
    { code: 'es', name: 'Spanish' },
    { code: 'fr', name: 'French' },
    { code: 'de', name: 'German' },
    { code: 'ar', name: 'Arabic' },
    { code: 'hi', name: 'Hindi' },
    { code: 'pt', name: 'Portuguese' },
  ];

  const handleTranscribe = async () => {
    setIsTranscribing(true);
    setError(null);
    setProgress(0);

    // Simulate transcription progress
    const progressInterval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 95) {
          clearInterval(progressInterval);
          return 95;
        }
        return prev + Math.random() * 15;
      });
    }, 500);

    try {
      // Simulate API call for transcription
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Mock transcription result
      const mockTranscription = "This is a sample transcription of the voice message. In a real implementation, this would be generated by a speech-to-text API like Google Cloud Speech-to-Text, Amazon Transcribe, or OpenAI Whisper.";
      
      setTranscription(mockTranscription);
      setProgress(100);
      
      if (onTranscriptionComplete) {
        onTranscriptionComplete(mockTranscription);
      }
    } catch (err) {
      setError('Failed to transcribe audio. Please try again.');
    } finally {
      clearInterval(progressInterval);
      setIsTranscribing(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(transcription);
  };

  const handleDownload = () => {
    const blob = new Blob([transcription], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'transcription.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-[#0b141a] rounded-lg p-4 space-y-4">
      {/* Language Selection */}
      <div className="flex items-center gap-3">
        <Languages size={18} className="text-[#00a884]" />
        <select
          value={selectedLanguage}
          onChange={(e) => setSelectedLanguage(e.target.value)}
          disabled={isTranscribing}
          className="bg-[#1a2e35] text-white px-3 py-2 rounded-lg border border-[#00a884]/30 focus:border-[#00a884] focus:outline-none text-sm"
        >
          {languages.map(lang => (
            <option key={lang.code} value={lang.code}>{lang.name}</option>
          ))}
        </select>
      </div>

      {/* Transcription Button */}
      {!transcription && !isTranscribing && (
        <button
          onClick={handleTranscribe}
          className="w-full bg-[#00a884] text-white py-3 rounded-lg font-medium hover:bg-[#008f72] transition-colors flex items-center justify-center gap-2"
        >
          <Mic size={20} />
          Transcribe Voice Note
        </button>
      )}

      {/* Progress */}
      {isTranscribing && (
        <div className="space-y-2">
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-400">Transcribing...</span>
            <span className="text-[#00a884]">{Math.round(progress)}%</span>
          </div>
          <div className="w-full bg-[#1a2e35] rounded-full h-2">
            <motion.div
              className="bg-[#00a884] h-2 rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="bg-red-500/20 border border-red-500/30 rounded-lg p-3 flex items-center gap-2">
          <X size={16} className="text-red-400" />
          <p className="text-red-400 text-sm">{error}</p>
        </div>
      )}

      {/* Transcription Result */}
      {transcription && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-3"
        >
          <div className="flex items-center gap-2 text-[#00a884]">
            <Check size={18} />
            <span className="font-medium">Transcription Complete</span>
          </div>

          <div className="bg-[#1a2e35] rounded-lg p-4">
            <p className="text-gray-200 text-sm whitespace-pre-wrap">{transcription}</p>
          </div>

          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="flex-1 bg-[#0b141a] text-white py-2 rounded-lg text-sm font-medium hover:bg-[#1a2e35] transition-colors flex items-center justify-center gap-2"
            >
              <Copy size={16} />
              Copy
            </button>
            <button
              onClick={handleDownload}
              className="flex-1 bg-[#0b141a] text-white py-2 rounded-lg text-sm font-medium hover:bg-[#1a2e35] transition-colors flex items-center justify-center gap-2"
            >
              <Download size={16} />
              Download
            </button>
            <button
              onClick={() => setTranscription('')}
              className="flex-1 bg-[#0b141a] text-gray-400 py-2 rounded-lg text-sm font-medium hover:text-white transition-colors flex items-center justify-center gap-2"
            >
              <X size={16} />
              Clear
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
};

// Voice Transcription Settings
export const TranscriptionSettings = ({ settings, onUpdate }) => {
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-white font-medium flex items-center gap-2">
            <FileText size={18} className="text-[#00a884]" />
            Voice Transcription
          </p>
          <p className="text-gray-400 text-sm">Auto-transcribe voice messages</p>
        </div>
        <button
          onClick={() => onUpdate({ ...settings, autoTranscribe: !settings.autoTranscribe })}
          className={`w-12 h-6 rounded-full transition-all ${
            settings.autoTranscribe ? 'bg-[#00a884]' : 'bg-[#0b141a]'
          }`}
        >
          <div
            className={`w-5 h-5 bg-white rounded-full transition-all ${
              settings.autoTranscribe ? 'translate-x-6' : 'translate-x-0.5'
            }`}
          />
        </button>
      </div>

      {settings.autoTranscribe && (
        <div className="space-y-3 pl-4 border-l-2 border-[#00a884]/30">
          <div>
            <p className="text-white text-sm mb-2">Default language</p>
            <select
              value={settings.defaultLanguage || 'en'}
              onChange={(e) => onUpdate({ ...settings, defaultLanguage: e.target.value })}
              className="w-full bg-[#0b141a] text-white px-4 py-3 rounded-lg border border-[#00a884]/30 focus:border-[#00a884] focus:outline-none"
            >
              <option value="en">English</option>
              <option value="sw">Swahili</option>
              <option value="es">Spanish</option>
              <option value="fr">French</option>
              <option value="de">German</option>
              <option value="ar">Arabic</option>
            </select>
          </div>

          <div className="flex items-center justify-between">
            <div>
              <p className="text-white text-sm">Auto-save transcriptions</p>
              <p className="text-gray-400 text-xs">Save transcriptions automatically</p>
            </div>
            <button
              onClick={() => onUpdate({ ...settings, autoSaveTranscriptions: !settings.autoSaveTranscriptions })}
              className={`w-12 h-6 rounded-full transition-all ${
                settings.autoSaveTranscriptions ? 'bg-[#00a884]' : 'bg-[#0b141a]'
              }`}
            >
              <div
                className={`w-5 h-5 bg-white rounded-full transition-all ${
                  settings.autoSaveTranscriptions ? 'translate-x-6' : 'translate-x-0.5'
                }`}
              />
            </button>
          </div>

          <div className="flex items-center justify-between">
            <div>
              <p className="text-white text-sm">Show in chat</p>
              <p className="text-gray-400 text-xs">Display transcription below voice note</p>
            </div>
            <button
              onClick={() => onUpdate({ ...settings, showTranscriptionInChat: !settings.showTranscriptionInChat })}
              className={`w-12 h-6 rounded-full transition-all ${
                settings.showTranscriptionInChat ? 'bg-[#00a884]' : 'bg-[#0b141a]'
              }`}
            >
              <div
                className={`w-5 h-5 bg-white rounded-full transition-all ${
                  settings.showTranscriptionInChat ? 'translate-x-6' : 'translate-x-0.5'
                }`}
              />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// Real-time Transcription Component
export const RealTimeTranscription = ({ isRecording, onTranscriptUpdate }) => {
  const [liveTranscript, setLiveTranscript] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    if (isRecording) {
      // Simulate real-time transcription
      const interval = setInterval(() => {
        const words = ['Hello', 'this', 'is', 'a', 'test', 'of', 'real-time', 'transcription'];
        const randomWord = words[Math.floor(Math.random() * words.length)];
        setLiveTranscript(prev => prev + ' ' + randomWord);
        
        if (onTranscriptUpdate) {
          onTranscriptUpdate(liveTranscript + ' ' + randomWord);
        }
      }, 1000);

      return () => clearInterval(interval);
    }
  }, [isRecording]);

  return (
    <div className="bg-[#0b141a]/50 rounded-lg p-3">
      <div className="flex items-center gap-2 mb-2">
        <div className={`w-2 h-2 rounded-full ${isRecording ? 'bg-red-500 animate-pulse' : 'bg-gray-500'}`} />
        <span className="text-gray-400 text-xs">
          {isRecording ? 'Live transcription' : 'Transcription paused'}
        </span>
      </div>
      {liveTranscript && (
        <p className="text-gray-300 text-sm">{liveTranscript}</p>
      )}
    </div>
  );
};

export default VoiceTranscription;
