import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useSearchParams, useLocation } from 'react-router-dom';
import { Eye, EyeOff, Lock, LogIn, Phone, ShieldCheck, ArrowLeft } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';

const Login = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [searchParams] = useSearchParams();
  // FIX: ProtectedRoute sends unauthenticated visitors here with
  // state={{ from: location }} (e.g. from a /join/:groupId/:code invite
  // link). Previously login always redirected to /chat afterward, which
  // silently dropped invite links. Honor that, or an explicit ?redirect=.
  const fromPath = location.state?.from
    ? `${location.state.from.pathname || ''}${location.state.from.search || ''}`
    : '';
  const redirectTarget = fromPath || searchParams.get('redirect') || '/chat';
  const { login } = useAuth();
  const [phoneNumber, setPhoneNumber] = useState('');
  const [password, setPassword] = useState('');
  const [twoFactorToken, setTwoFactorToken] = useState('');
  const [requiresTwoFactor, setRequiresTwoFactor] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [locked, setLocked] = useState(false);
  const [lockMinutes, setLockMinutes] = useState(0);
  const [apkVersion, setApkVersion] = useState(null);

  // Show the current Android build (from version.json, generated by
  // npm run apk:build) next to the download button so users can check
  // whether they have the latest version.
  useEffect(() => {
    fetch('/version.json')
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        if (data?.version) setApkVersion(data);
      })
      .catch(() => {}); // graceful: banner simply won't show
  }, []);

  const handleError = (err, fallback) => {
    const msg = err?.message || fallback || 'Network error. Please check your connection.';
    if (err?.status === 423) {
      const minutes = Number((msg.match(/in (\d+) minute/) || [])[1] || 0);
      setLocked(true);
      setLockMinutes(minutes);
      setError('');
    } else {
      setError(err?.warning ? `${msg} (${err.warning})` : msg);
    }
  };

  const handleCredentialsLogin = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const data = await login({ identifier: phoneNumber, password });

      if (data?.requiresTwoFactor) {
        setRequiresTwoFactor(true);
        setTwoFactorToken('');
        return;
      }

      if (data?.requiresPhoneVerification) {
        navigate('/verify-phone', { replace: true });
        return;
      }

      if (data?.success !== false && data?.token) {
        toast.success('Login successful!');
        navigate(redirectTarget, { replace: true });
      } else {
        setError(data?.message || 'Invalid credentials');
        setPassword('');
      }
    } catch (err) {
      handleError(err, 'Invalid credentials');
      setPassword('');
    } finally {
      setLoading(false);
    }
  };

  const handleTwoFactorSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const data = await login({ identifier: phoneNumber, password, twoFactorToken });

      if (data?.success !== false && data?.token) {
        toast.success('Login successful!');
        navigate(redirectTarget, { replace: true });
      } else {
        setError(data?.message || 'Invalid two-factor code');
      }
    } catch (err) {
      handleError(err, 'Invalid two-factor code');
    } finally {
      setLoading(false);
    }
  };

  const handleBackToCredentials = () => {
    setRequiresTwoFactor(false);
    setTwoFactorToken('');
    setError('');
  };

  return (
    <div className="min-h-screen flex items-center justify-center px-4" style={{ background: 'radial-gradient(900px 600px at 20% 15%, rgba(255,45,120,0.22), transparent 55%), radial-gradient(800px 600px at 85% 85%, rgba(124,92,255,0.22), transparent 55%), radial-gradient(700px 500px at 65% 30%, rgba(0,217,166,0.12), transparent 50%), #0c0a1e' }}>
      {requiresTwoFactor ? (
        <form onSubmit={handleTwoFactorSubmit} className="w-full max-w-md bg-[#111b21] border border-white/10 rounded-lg p-6 shadow-2xl genz-card">
          <div className="mb-6">
            <h1 className="genz-display text-3xl text-white">GENZ</h1>
            <p className="genz-hand text-xl text-[#ffd447] mt-1">Two-Factor Authentication</p>
            <p className="text-sm text-slate-400 mt-1">
              Enter the 6-digit code from your authenticator app for{' '}
              <span className="text-slate-200">{phoneNumber}</span>.
            </p>
          </div>

          {error && (
            <div className="mb-4 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">
              {error}
            </div>
          )}

          <label className="block text-sm text-slate-300 mb-2">Msimbo wa 2FA</label>
          <div className="mb-6 flex items-center gap-2 rounded-md bg-[#202c33] border border-white/10 px-3">
            <ShieldCheck size={18} className="text-[#00a884]" />
            <input
              value={twoFactorToken}
              onChange={(event) => setTwoFactorToken(event.target.value.replace(/[^\d]/g, '').slice(0, 6))}
              className="w-full bg-transparent py-3 text-white outline-none tracking-widest"
              placeholder="000000"
              inputMode="numeric"
              autoComplete="one-time-code"
              maxLength={6}
              required
              autoFocus
            />
          </div>

          <button
            type="submit"
            disabled={loading || twoFactorToken.length !== 6}
            className="w-full flex items-center justify-center gap-2 rounded-md bg-[#ff2d78] hover:bg-[#d61a5e] py-3 font-bold text-white transition-colors disabled:opacity-60 genz-sticker"
          >
            <ShieldCheck size={18} />
            {loading ? 'Inathibitisha...' : 'Verify'}
          </button>

          <button
            type="button"
            onClick={handleBackToCredentials}
            className="mt-4 w-full flex items-center justify-center gap-1 text-sm text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft size={16} /> Back to login
          </button>
        </form>
      ) : (
        <form onSubmit={handleCredentialsLogin} className="w-full max-w-md bg-[#111b21] border border-white/10 rounded-lg p-6 shadow-2xl genz-card">
          <div className="mb-6">
            <h1 className="genz-display text-3xl text-white">GENZ</h1>
            <p className="genz-hand text-xl text-[#ffd447] mt-1">Login</p>
            <p className="text-sm text-slate-400 mt-1">Log in to your account to continue.</p>
          </div>

          {error && (
            <div className="mb-4 rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">
              {error}
            </div>
          )}

          {locked && (
            <div className="mb-4 rounded-md border border-orange-500/40 bg-orange-500/10 px-3 py-3 text-sm text-orange-200">
              <p className="font-semibold mb-1">Account temporarily locked</p>
              <p>Too many failed login attempts. Try again in {lockMinutes} minute{lockMinutes === 1 ? '' : 's'}.</p>
            </div>
          )}

          <label className="block text-sm text-slate-300 mb-2">
            Namba ya simu au username (e.g. +255...)
          </label>
          <div className="mb-4 flex items-center gap-2 rounded-md bg-[#202c33] border border-white/10 px-3">
            <Phone size={18} className="text-[#00a884]" />
            <input
              value={phoneNumber}
              onChange={(event) => setPhoneNumber(event.target.value)}
              className="w-full bg-transparent py-3 text-white outline-none"
              placeholder="+255712345678"
              autoComplete="tel"
              disabled={locked}
              required
            />
          </div>

          <label className="block text-sm text-slate-300 mb-2">Nenosiri</label>
          <div className="mb-6 flex items-center gap-2 rounded-md bg-[#202c33] border border-white/10 px-3">
            <Lock size={18} className="text-slate-400" />
            <input
              type={showPassword ? 'text' : 'password'}
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              className="w-full bg-transparent py-3 text-white outline-none"
              autoComplete="current-password"
              disabled={locked}
              required
            />
            <button type="button" onClick={() => setShowPassword((value) => !value)} className="text-slate-300">
              {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>

          <button
            type="submit"
            disabled={loading || locked}
            className="w-full flex items-center justify-center gap-2 rounded-md bg-[#ff2d78] hover:bg-[#d61a5e] py-3 font-bold text-white transition-colors disabled:opacity-60 genz-sticker"
          >
            <LogIn size={18} />
            {loading ? 'Logging in...' : 'Login'}
          </button>

          <div className="mt-5 flex items-center justify-between text-sm">
            <Link to="/forgot-password" className="text-[#00a884] hover:text-white transition-colors">Forgot password?</Link>
            <Link to="/register" className="text-slate-300 hover:text-white transition-colors">Create account</Link>
          </div>

          <div className="mt-6 border-t border-white/10 pt-4 flex items-center justify-center gap-4 text-xs text-slate-500">
            <Link to="/terms" className="hover:text-[#00a884] transition-colors">Terms</Link>
            <span className="text-white/15">•</span>
            <Link to="/privacy-policy" className="hover:text-[#00a884] transition-colors">Privacy Policy</Link>
          </div>

          <a
            href="/genz-whatsapp.apk"
            download="genz-whatsapp.apk"
            className="mt-4 w-full flex items-center justify-center gap-2 rounded-md border border-[#00a884]/40 bg-[#00a884]/10 hover:bg-[#00a884]/20 py-2.5 text-sm font-semibold text-[#00a884] transition-colors"
            title="Download the Android app (APK)"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download Android App
          </a>
          {apkVersion && (
            <p className="mt-2 text-center text-[11px] text-slate-500">
              GENZ WhatsApp Android v{apkVersion.version}
            </p>
          )}
          <p className="mt-1 text-center text-[11px] text-slate-600">
            <Link to="/install" className="text-[#00a884]/70 hover:text-[#00a884]">
              How to install — Jinsi ya kusakinisha
            </Link>
          </p>
        </form>
      )}
    </div>
  );
};

export default Login;
